### ISSUE TITLE
remove x-select.js

### ISSUE THREAD

**Issue by cowboyd** [thefrontside/emberx-select-blockless#1]
It looks like somehow `x-select.js` survived from the extraction. We should remove it from the source since it is always coming from x-select anyhow.

**Comment by coferc** [comment]
Hi, I downloaded this today so I could easily rid of my Ember.SelectView (thanks for the similar syntax!) while upgrading to Glimmer, but it looks like the “Blockless Single” and “Blockless Single w/Option Value” are both broken. (See it broken in your demo page, http://thefrontside.github.io/emberx-select/blockless-single). It looks like in the emberx-select/components/x-select.js file, the _updateValueSingle function is missing the line, **this.raiseAction()**, whereas the _updateValueMultiple function has this line so the Blockless Multiple is working. I believe this open issue is about sourcing x-select from the other file, emberx-select-blockless/components/x-select.js, where I can see the action raising should work for both cases since it's in the "change" function.

**Comment by coferc** [comment]
When I used value instead of selection per the updated README, it worked. I was following the example in the tests/dummy/app which referenced selection.

**Comment by Robdel12** [comment]
Awesome :) I was just about to jump in and see if I could help.

**Comment by cowboyd** [comment]
Yeah, sorry about the confusion, we've literally just extracted this component from mainline `x-select`, so you're probably one of the earliest adopters :)
